export const INPUT_CREATED = "INPUT_CREATED";
export const INPUT_UPDATE = "INPUT_UPDATE";
export const INPUT_UPDATE_TRIGGER = "INPUT_UPDATE_TRIGGER";
export const INPUT_DELETE = "INPUT_DELETE";
export const INPUT_INITIAL = "INPUT_INITIAL";
